// Each chest contains 50 choices commonly found in Ho Chi Minh City.
export const chestCatalog: Record<number, string[]> = {
  1: 'Cơm tấm sườn bì chả|Cơm tấm sườn trứng|Cơm tấm sườn bì|Cơm tấm ba rọi nướng|Cơm tấm gà nướng|Cơm gà xối mỡ|Cơm gà Hải Nam|Cơm gà rô-ti|Cơm gà chiên nước mắm|Cơm chiên Dương Châu|Cơm chiên hải sản|Cơm chiên cá mặn|Cơm chiên kim chi|Cơm bò lúc lắc|Cơm bò kho|Cơm thịt kho trứng|Cơm cá kho tộ|Cơm cá chiên|Cơm thịt nướng|Cơm sườn ram|Cơm heo quay|Cơm vịt quay|Cơm xá xíu|Cơm cà ri gà|Cơm cà ri bò|Cơm niêu cá kho|Cơm niêu cháy kho quẹt|Cơm phần gà chiên|Cơm phần cá basa kho|Cơm phần thịt rim|Cơm văn phòng|Cơm bình dân|Cơm trứng ốp la|Cơm chả trứng|Cơm chả cá|Cơm nem nướng|Cơm thịt xiên nướng|Cơm sườn non nướng|Cơm sườn cốt lết|Cơm gà sốt mắm tỏi|Cơm thịt bò xào|Cơm tôm rim|Cơm mực xào|Cơm cá thu sốt cà|Cơm thịt quay|Xôi mặn|Xôi gà|Xôi thịt|Xôi xá xíu|Xôi bắp'.split('|'),
  2: 'Phở bò tái|Phở bò chín|Phở tái nạm|Phở bò viên|Phở gà|Phở gà trộn|Bún bò Huế|Bún riêu cua|Bún riêu ốc|Bún thịt nướng|Bún nem nướng|Bún mắm|Bún cá|Bún chả cá|Bún mọc|Bún măng vịt|Bún ngan|Bún đậu mắm tôm|Bún thái hải sản|Bún bò Nam Bộ|Hủ tiếu Nam Vang|Hủ tiếu mì|Hủ tiếu khô|Hủ tiếu bò kho|Hủ tiếu sa tế|Hủ tiếu mực|Hủ tiếu gõ|Mì Quảng tôm thịt|Mì Quảng gà|Mì vịt tiềm|Mì hoành thánh|Mì xá xíu|Mì sủi cảo|Miến gà|Miến cua|Miến lươn|Bánh canh cua|Bánh canh giò heo|Bánh canh cá lóc|Bánh canh ghẹ|Cháo lòng|Cháo gà|Cháo vịt|Cháo sườn|Cháo cá|Súp cua|Bò kho bánh mì|Bò kho hủ tiếu|Lẩu Thái|Lẩu gà lá é'.split('|'),
  3: 'Bánh tráng trộn|Bánh tráng nướng|Bánh tráng cuốn bơ|Bánh tráng chấm|Bánh tráng kẹp|Gỏi khô bò|Gỏi đu đủ khô bò|Phá lấu bò|Phá lấu mì gói|Bắp xào|Khoai tây lắc|Khoai lang lắc|Cá viên chiên|Bò viên chiên|Xúc xích chiên|Hồ lô chiên|Xiên que chiên|Chân gà sả tắc|Chân gà nướng|Cút lộn xào me|Trứng cút lộn xào me|Ốc hương rang muối|Ốc len xào dừa|Ốc móng tay xào rau muống|Ốc cà na rang muối|Ốc bươu nhồi thịt|Sò điệp nướng mỡ hành|Sò huyết rang me|Nghêu hấp sả|Hàu nướng phô mai|Hàu nướng mỡ hành|Tôm nướng muối ớt|Bạch tuộc nướng sa tế|Mực nướng sa tế|Càng ghẹ rang muối|Cua rang me|Cua sốt bơ tỏi|Gà nướng muối ớt|Gà chiên nước mắm|Cánh gà chiên mắm|Chim cút chiên bơ|Bắp bò ngâm mắm|Khô mực nướng|Khô gà lá chanh|Da gà chiên giòn|Đậu hũ chiên sả|Đậu hũ trứng chiên|Sụn gà rang muối|Lòng gà xào mướp|Bò lá lốt'.split('|'),
  4: 'Chè ba màu|Chè đậu xanh|Chè đậu đỏ|Chè đậu đen|Chè đậu trắng|Chè bưởi|Chè khúc bạch|Chè Thái|Chè sương sa hạt lựu|Chè sương sáo|Chè trôi nước|Chè bà ba|Chè chuối|Chè khoai dẻo|Chè khoai môn|Chè bắp|Chè hạt sen|Chè long nhãn|Chè dưỡng nhan|Chè nha đam|Tàu hũ nước đường|Tàu hũ đá|Bánh flan|Bánh bò nướng|Bánh bò hấp|Bánh da lợn|Bánh chuối hấp|Bánh chuối nướng|Bánh khoai mì nướng|Bánh ít ngọt|Bánh pía|Bánh cốm|Bánh đậu xanh|Bánh gai|Bánh phu thê|Bánh cam|Bánh rán mật|Bánh tiêu|Bánh tai yến|Bánh dừa nướng|Bánh kẹp|Rau câu dừa|Rau câu lá dứa|Sương sáo nước cốt dừa|Kem xôi|Kem dừa|Kem bơ|Kem chuối|Trái cây dầm|Sinh tố trái cây'.split('|'),
  5: 'Cơm chay thập cẩm|Cơm chay đậu hũ|Cơm chay nấm|Cơm chay rau củ|Cơm chay lá sen|Cơm chay gạo lứt|Cơm chiên chay|Bún chay|Bún riêu chay|Bún bò Huế chay|Bún măng chay|Bún thịt nướng chay|Bún đậu chay|Phở chay|Phở cuốn chay|Mì Quảng chay|Mì xào chay|Mì nước chay|Hủ tiếu chay|Miến chay|Bánh canh chay|Cháo chay|Lẩu chay|Lẩu nấm|Lẩu Thái chay|Gỏi cuốn chay|Chả giò chay|Bánh xèo chay|Bánh khọt chay|Bánh cuốn chay|Bánh bột lọc chay|Bánh tráng cuốn chay|Đậu hũ sốt cà|Đậu hũ kho nấm|Đậu hũ chiên sả|Đậu hũ non sốt nấm|Nấm kho tiêu|Nấm rơm kho|Nấm đùi gà nướng|Rau củ kho quẹt|Rau củ xào|Cà tím kho chay|Cà ri chay|Bò kho chay|Gà rô-ti chay|Cá kho chay|Chả lụa chay|Gỏi ngó sen chay|Salad chay|Bánh mì chay'.split('|'),
  6: 'Cà phê sữa đá|Bạc xỉu|Cà phê đen đá|Cà phê muối|Cà phê dừa|Cold brew|Espresso tonic|Latte|Mocha|Caramel macchiato|Matcha latte|Matcha dừa|Matcha xoài|Matcha dâu|Cacao sữa|Chocolate đá xay|Cookies and cream|Hồng trà sữa|Ô long sữa|Trà sữa trân châu đường đen|Trà sữa khoai môn|Trà sữa chocolate|Trà sữa pudding|Trà sữa kem cheese|Trà đào cam sả|Ô long đào|Trà vải|Trà dâu|Trà mãng cầu|Trà mận|Trà ổi hồng|Trà bưởi nha đam|Trà chanh dây|Trà tắc|Trà sữa Thái xanh|Nước mía tắc|Rau má đậu xanh|Sữa tươi trân châu đường đen|Sữa chua uống|Dừa tắc|Nước sâm|Nước ép cam|Nước ép ổi|Nước ép thơm|Sinh tố bơ|Sinh tố xoài|Sinh tố dâu|Sinh tố mãng cầu|Soda chanh dây|Yaourt đá'.split('|')
};
